-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMWwzafISUMwIzIDj
kjZ8iWB7p+NmtG+mAEUTJA5f6tegCgYIKoZIzj0DAQehRANCAASLh4f5ojGv7AGv
a6IX4FmzIk61CfLGpLwJyVOOy/H0k6hcKfUZjv99lL6biIuFkTWrlY1SkHNvqgU3
0MrCLAUj
-----END PRIVATE KEY-----